find_path(_rax_INCLUDE_DIR rax)
find_library(_rax_LIB rax)
if(_rax_INCLUDE_DIR AND _rax_LIB)
    message(STATUS "Found rax:")
    message(STATUS "  include: ${_rax_INCLUDE_DIR}")
    message(STATUS "  lib: ${_rax_LIB}")
    add_library(rax::rax UNKNOWN IMPORTED)
    set_target_properties(rax::rax PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_rax_INCLUDE_DIR}")
    set_property(TARGET rax::rax APPEND PROPERTY IMPORTED_LOCATION "${_rax_LIB}")
    unset(_rax_LIB)
    unset(_rax_INCLUDE_DIR)
    set(rax_FOUND TRUE)
else()
    message(STATUS "NOT Found rax")
    set(rax_FOUND FALSE)
endif()
