find_path(CPPITERTOOLS_INCLUDE_DIR cppitertools)
if(CPPITERTOOLS_INCLUDE_DIR)
    message(STATUS "Found cppitertools: ${CPPITERTOOLS_INCLUDE_DIR}")
    set(cppitertools_FOUND TRUE)
    add_library(cppitertools INTERFACE IMPORTED)
    target_include_directories(cppitertools INTERFACE ${CPPITERTOOLS_INCLUDE_DIR})
else()
    set(cppitertools_FOUND FALSE)
endif()
